### ISSUE TITLE
RT 4.4.3 vanilla Error

### ISSUE THREAD

**Issue by tbrumm** [NETWAYS/rt-extension-ticketactions#19]
Some Errors on vanilla RT 4.4.3

[92355] [Wed Jan 23 09:10:37 2019] [error]: Error during compilation of /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccess:
Bareword found where operator expected at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccess line 9, near "s~^/~~r"
syntax error at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccess line 9, near "s~^/~~r "

Stack:
  [/usr/local/share/perl5/HTML/Mason/Interp.pm:450]
  [/usr/local/share/perl5/HTML/Mason/Request.pm:1127]
  [/usr/local/share/perl5/HTML/Mason/Request.pm:1060]
  [/usr/local/share/perl5/HTML/Mason/Request.pm:1239]
  [/opt/rt4/local/plugins/RT-Extension-TicketActions/html/Callbacks/RT-Extension-TicketActions/Ticket/Elements/ShowSummary/LeftColumnTop:1]
  [/opt/rt4/share/html/Ticket/Elements/ShowSummary:51]
  [/opt/rt4/share/html/Ticket/Display.html:74]
  [/opt/rt4/share/html/Widgets/TitleBox:61]
  [/opt/rt4/share/html/Ticket/Display.html:75]
  [/opt/rt4/share/html/Ticket/autohandler:66]
  [/opt/rt4/sbin/../lib/RT/Interface/Web.pm:697]
  [/opt/rt4/sbin/../lib/RT/Interface/Web.pm:376]
  [/opt/rt4/share/html/autohandler:53] (/opt/rt4/sbin/../lib/RT/Interface/Web/Handler.pm:208)

## Your Environment
* latest version from this repo:
* RT 4.4.3:
* RHEL 6.2:
* Perl 5.10.1:

**Comment by mxhash** [comment]
Hi Torsten,

thanks for testing. Interesting, this is not a conventional syntax error. Maybe a more conventional approach works:

    <% $entry->path =~ s/^\///r %>

or, easier, just drop the substitution:

    <% $entry->path %>

Cheers,
Marius

**Comment by tbrumm** [comment]
Hi Marius,
tried out both, no success:
[103543] [Wed Jan 23 10:28:51 2019] [error]: Error during compilation of /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccess:
Bareword found where operator expected at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccess line 9, near "s/^\///r"
syntax error at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccess line 9, near "s/^\///r "


Stack:
  [/usr/local/share/perl5/HTML/Mason/Interp.pm:450]
  [/usr/local/share/perl5/HTML/Mason/Request.pm:1127]
  [/usr/local/share/perl5/HTML/Mason/Request.pm:1060]
  [/usr/local/share/perl5/HTML/Mason/Request.pm:1239]
  [/opt/rt4/local/plugins/RT-Extension-TicketActions/html/Callbacks/RT-Extension-TicketActions/Ticket/Elements/ShowSummary/LeftColumnTop:1]
  [/opt/rt4/share/html/Ticket/Elements/ShowSummary:51]
  [/opt/rt4/share/html/Ticket/Display.html:74]
  [/opt/rt4/share/html/Widgets/TitleBox:61]
  [/opt/rt4/share/html/Ticket/Display.html:75]
  [/opt/rt4/share/html/Ticket/autohandler:66]
  [/opt/rt4/sbin/../lib/RT/Interface/Web.pm:697]
  [/opt/rt4/sbin/../lib/RT/Interface/Web.pm:376]
  [/opt/rt4/share/html/autohandler:53] (/opt/rt4/sbin/../lib/RT/Interface/Web/Handler.pm:208)
[Wed Jan 23 10:29:22 2019] [notice] caught SIGTERM, shutting down
[Wed Jan 23 10:29:22 2019] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jan 23 10:29:22 2019] [notice] Digest: generating secret for digest authentication ...
[Wed Jan 23 10:29:22 2019] [notice] Digest: done
[Wed Jan 23 10:29:22 2019] [notice] Apache/2.2.15 (Unix) DAV/2 mod_fcgid/2.3.7 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[103679] [Wed Jan 23 10:29:28 2019] [error]: Error during compilation of /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccessSearch:
Bareword found where operator expected at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccessSearch line 47, near "s/^[< ]+//r"
Bareword found where operator expected at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccessSearch line 52, near "s/^[< ]+//r"
Bareword found where operator expected at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccessSearch line 67, near "s/[ >]+$//r"
Bareword found where operator expected at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccessSearch line 72, near "s/[ >]+$//r"
Bareword found where operator expected at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccessSearch line 8, near "s~^/~~r"
syntax error at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccessSearch line 47, near "s/^[< ]+//r"
syntax error at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccessSearch line 52, near "s/^[< ]+//r"
syntax error at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccessSearch line 67, near "s/[ >]+$//r"
syntax error at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccessSearch line 72, near "s/[ >]+$//r"
syntax error at /opt/rt4/local/plugins/RT-Extension-TicketActions/html/Ticket/Elements/RT-Extension-TicketActions-QuickAccessSearch line 8, near "s~^/~~r "


Stack:
  [/usr/local/share/perl5/HTML/Mason/Interp.pm:450]
  [/usr/local/share/perl5/HTML/Mason/Request.pm:1127]
  [/usr/local/share/perl5/HTML/Mason/Request.pm:1060]
  [/usr/local/share/perl5/HTML/Mason/Request.pm:1239]
  [/opt/rt4/local/plugins/RT-Extension-TicketActions/html/Callbacks/RT-Extension-TicketActions/Ticket/Elements/ShowSummary/LeftColumnTop:2]
  [/opt/rt4/share/html/Ticket/Elements/ShowSummary:51]
  [/opt/rt4/share/html/Ticket/Display.html:74]
  [/opt/rt4/share/html/Widgets/TitleBox:61]
  [/opt/rt4/share/html/Ticket/Display.html:75]
  [/opt/rt4/share/html/Ticket/autohandler:66]
  [/opt/rt4/sbin/../lib/RT/Interface/Web.pm:697]
  [/opt/rt4/sbin/../lib/RT/Interface/Web.pm:376]
  [/opt/rt4/share/html/autohandler:53] (/opt/rt4/sbin/../lib/RT/Interface/Web/Handler.pm:208)
:-/

**Comment by mxhash** [comment]
Allright, was just a quick shot. I'll need to do some more tests to reproduce.

**Comment by tbrumm** [comment]
Great, i will check the other Addons from you ;-) The UserSearch works great, love to see it running in our huge Environment ;-)

**Comment by mxhash** [comment]
Hi, created a PR for that issue.

Best,
Marius
